### ISSUE TITLE
Stops updating lights after ~30 min of use

### ISSUE THREAD

**Issue by bnknkl** [Tagueo/icue-ambilight#1]
Hey, this is super great! Noticed that after about 30 minutes of activity, the app stops updating the lights. Feeds appear to be normal in the app itself, though. Issue appears to be resolved by quitting the app, launching iCue, and then relaunching the app.

**Comment by Tagueo** [comment]
Hi, thanks for the feedback ! For now I haven't been able to reproduce this issue. 
However there is a similar issue when you minimize the window or hide the capture previews, so maybe that's the cause.
If it happens again could you check the console (ctrl+shift+i) for any errors ?
Thanks again :D

**Comment by TechBear74** [comment]
Hi I would like to add that after some time it does seem to stop working and it seems corsair icue crashes as well.

**Comment by straylightrun89** [comment]
Fantastic job on this program mate! been waiting years for something similar. I just wanted to add that I am also experiencing the bug of ICUE crashing after roughly half an hour. 1 thing I have noticed is the preview for my second monitor becomes all pixellated as shown in the attached picture, which is then fixed when ICUE and ambilight are reloaded.
![ambilight](https://user-images.githubusercontent.com/21089727/70581823-7f010e80-1bf3-11ea-9a9d-7c566e6570c6.png)

**Comment by mattgphoto** [comment]
Yep, can confirm, iCUE crashes, and this app stops updating the lights on the corsair devices. Takes longer than a half hour for me though.

**Comment by Tagueo** [comment]
Hi again, and sorry for being absent for so long. My guess is that this was caused by the early version of the cue sdk I was using back then. The program used to be very memory hungry for an unknown reason. I'll left the issue open if someone encounters it again since I can't really say if it is currently solved.
