### ISSUE TITLE
Disable all but LS100?

### ISSUE THREAD

**Issue by Rygar1976** [Tagueo/icue-ambilight#13]
Hi there - just wondering if it's possible to easily disable the lighting on my PC and have this app ONLY affect the LS100 + 450mm extension kit I have on my TV?  Right now, it lights up the 14 Corsair QL and ML RGB pros inside my case (at a lower brightness) along with the LS100 kit.  
I can disable the 2 lighting nodes in my case by changing the lighting setup, but of course lighting setup isn't part of the profiles in iCue that gets saved per profile... more Corsair BS.  

Also - I am using a 65" LG C9 OLED TV and there really isnt a good way to run the lighting strips along the bottom of the TV to make the typical rectangle shape they intend.  Instead - I ran all 4 x 450mm and 2 x 250 strips from the bottom left corner on the back, up across the entire top and down to the bottom right side.  It basically fills the entire area with lights, and looks nice due to not having gaps between strips.  
*Do you know how many of these extensions I can add before they wont run off 1 channel on the LS100 control box?  Am I already maxed out?  
I'd like to keep it this way but of course, im not sure the lights line up properly with where your software (or Corsairs crappy version) thinks the lights are.
I dont think I can add more strips, and it looks kinda weird to have the big gaps between two 450mm strips on the top, but I may not have a choice to get this to work properly.

It seems if I change the layout from the standard Corsair built in layout, the ambilighting cant be turned on anymore... ill have to try that with yours. 

I also just bought the LT120 Starter Kit - the 2 external RGB Towers.  I am going to hook them up as well and place them on either side or behind the tv for more lighting and to see if it adds to the effect at all... 

Id LOVE to do this via Phillips, but NOT through a HDMI 2.0 passthrough... your solution doesnt even seem to affect my FPS.  AMAZING!   Ive been telling everyone about your app!  lol  Thank you!!

**Comment by Tagueo** [comment]
Hi, sorry for being so late.

Concerning your questions about the software :
For now I don't have implemented such a feature. A good workaround would be to lower the brightness of the devices you don't want the software to affect in iCue's settings. But this is a great enhancement I could easily add. 

About your question on the LS100, I have absolutely no clue x)
One more problem is that I don't have a LS100 kit to test things out and that iCue does not offer a software demo for it, but I don't think the way its handled by the software differ from any other device.

Thanks for trying the app and telling your friends about it 😄

**Comment by Tagueo** [comment]
Hi! I have now implemented this feature in the latest release, so you can now select which devices you want to enable or disable in the layout section of the app. If you have any problem/suggestion with this feature feel free to open a new issue!
