### ISSUE TITLE
Video Capture window is blank.

### ISSUE THREAD

**Issue by pallyben** [Tagueo/icue-ambilight#15]
Hey,

This used to work great for me but now I cannot seem to get it to work. The program is detecting all of my monitors and refreshing properly, but the video capture window doesnt change.
I also have my icue software set to everything off so that this can take priority. 
thanks!

![video capture blank](https://user-images.githubusercontent.com/38229765/98394777-40551d80-2029-11eb-80c4-b05ed06b3ada.PNG)

**Comment by costispavlou** [comment]
same issue

**Comment by Tagueo** [comment]
Have you enabled the sdk support in iCue's settings ? The captures are not showing anything because there is no devices recognized.
