### ISSUE TITLE
Ram Dominator No working

### ISSUE THREAD

**Issue by Gork56** [Tagueo/icue-ambilight#16]
Please, I am french and my english is very bad

The ram Dominator corsair prem;ium no working with your Icue ambilight

please it's possible .

ciao

**Comment by Tagueo** [comment]
Bonjour, coup de chance, je suis français aussi 😉
Pouvez vous essayer de télécharger la dernière version du programme et envoyer une capture d'écran des périphériques connectés dans la partie "settings" ?
Merci d'avance 😉

**Comment by Gork56** [comment]
Bonjour ,
Non ca y est cela fonctionne il fallait juste cocher une case dans les options ICue.
Vivement de l'intégration dans des jeux comme CSgo , witcher 3 etc...
Merci de ton retour .
Envoyé depuis Yahoo Mail pour Android 
 
  Le sam., déc. 19, 2020 à 18:12, Augustin<notifications@github.com> a écrit :   


Bonjour, coup de chance, je suis français aussi 😉
Pouvez vous essayer de télécharger la dernière version du programme et envoyer une capture d'écran des périphériques connectés dans la partie "settings" ?
Merci d'avance 😉

**Comment by Tagueo** [comment]
Merci également de ton retour 😃

**Comment by Xoto1162** [comment]
> Bonjour , Non ca y est cela fonctionne il fallait juste cocher une case dans les options ICue. Vivement de l'intégration dans des jeux comme CSgo , witcher 3 etc... Merci de ton retour . Envoyé depuis Yahoo Mail pour Android Le sam., déc. 19, 2020 à 18:12, Augustin<notifications@github.com> a écrit : Bonjour, coup de chance, je suis français aussi 😉 Pouvez vous essayer de télécharger la dernière version du programme et envoyer une capture d'écran des périphériques connectés dans la partie "settings" ? Merci d'avance 😉 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Bonjour quel est la case que vous avez coché ?
Car j'ai le même problème tout fonctionne sauf pour la RAM Corsair Dominator Platinium pourtant tout apparait bien dans les settings

![image](https://user-images.githubusercontent.com/13108023/109304460-9e0daf80-783c-11eb-8d61-bc6e503053be.png)

**Comment by Gork56** [comment]
Bonjour,
Alors si je me souviens bien , car j'ai changé de configuration vers le lian-li.

Il y a dans l'onglet de la ram dans les paramètres généraux, je crois que c'est vers les derniers onglets . Il faut cocher une case et aussi il faut cocher la case sdk . Il faut tout essayer et redémarrer le logiciel a chaque fois.
