### ISSUE TITLE
Not controlling all devices, 1.4 wont let me select any options.

### ISSUE THREAD

**Issue by Oman395** [Tagueo/icue-ambilight#22]
I have an m65, a void elite, an h100i, 4x8 vengeance rgb pro, commander pro with 5xll120 and 4x rgb strips, and an asus motherboard. When I try to launch, only the m65 and h100i sync up. On top of that, in ver 1.4, I cannot select any option-- I try to click layout, for example, and it does nothing. What should I do?

**Comment by Tagueo** [comment]
Hi, could you check that you have enabled the sdk in iCue (check the readme for how to do this) ? if you have, please press ctrl+maj+i in icue-ambilight and post a screenshot of the content of the "console" section, thank you!

**Comment by Kvoo** [comment]
> I have the same issue. It's not working. If i uncheck a device, my leds turn off. The only way to make them turn on again is to close icue ambilight. I have SDK enabled.

The problem seems to be my headset. It's a corsair void elite Wireless, and it does have LEDs. When i unplug the dongle, it works.

**Comment by KStudios-zz** [comment]
Hello, I'm having the same here. Here are my logs: 

![image](https://user-images.githubusercontent.com/16726035/104962352-25f7d280-59d0-11eb-814a-7dd747bdbb53.png)

**Comment by Tagueo** [comment]
> The problem seems to be my headset. It's a corsair void elite Wireless, and it does have LEDs. When i unplug the dongle, it works.

So this would be related to #18
I'll work on a fix this weekend, the only problem is that I have no headset to try this so I'm not 100% sure this will work.

**Comment by Oman395** [comment]
OK quick update: unplugging the headset, launching ambilight, and plugging the headset back in it works. Vengeance rgb still arent lighting but i'm guessing they just arent implemented, or maybe theres a limit on devices lol

**Comment by Tagueo** [comment]
Hi again, thanks for your additional feedback.
I've pushed a release that *should* have fixed the problem.
Once again, I have no device able to reproduce this issue so I'm not sure that this will work.
I'll close the related issues when I'll be sure this is fixed!
