### ISSUE TITLE
[BUG] Unable to switch between tabs

### ISSUE THREAD

**Issue by afalk42** [Tagueo/icue-ambilight#23]
**Describe the bug**
I can see the Sources tab and the only option there is "Entire Screen", which is selected. But I am unable to click on either the Layout, Capture Previews, or Settings tabs at all - they are unresponsive.

**Please check that you have enabled the SDK in _ICUE_ (see the readme) before posting an issue**
I have enabled the SDK.

**To Reproduce**
1) Launch the application
2) Try clicking on any of the other three tabs - they are unresponsive

**Screenshots**

**Additional Information (please complete):**
 - Version : 1.4.0
 - Screenshot/paste of the logs :  (press Ctrl+Maj+I to access them) unable to access them. what the heck is a "Maj" key?????
 - Screenshot of the connected devices in **icue-ambilight**: unable to access Settings tab
 - Screenshot of the connected devices in **iCue**: 
![Screenshot 2021-01-22 190547](https://user-images.githubusercontent.com/6906332/105562745-77ae9e80-5ce9-11eb-84db-529299096c2f.png)

**Additional context**
Add any other relevant information about the problem here.

**Comment by Tagueo** [comment]
Hi, this is probably related to #22 although I can't be 100% sure.
About the Maj key, it is actually the french for the Shift key, this went out of my mind when writing the template, so thanks for pointing that out! 
I'll try to work on a fix this week-end, but thanks to the fact that I have no device able to reproduce this issue I'm not sure that this will work.
Thanks again for reporting the issue!

**Comment by afalk42** [comment]
Thank you for explaining the Maj key to me - very good to know. Here is the log:
![image](https://user-images.githubusercontent.com/6906332/105594455-29d57d00-5d61-11eb-94f1-e0d34264c2fb.png)
With respect to this being similar to #22 - I don't have a Corsair headset plugged in, but I do have Logitech G Hub keyboard, mouse, headset, and webcam plugged in. While the keyboard and mouse do have LEDs, they are not controllable by iCue, as they use a separate software for LED control.

**Comment by Tagueo** [comment]
Hi again, thanks for your additional feedback.
I've pushed a release that *should* have fixed the problem.
Once again, I have no device able to reproduce this issue so I'm not sure that this will work.
I'll close the related issues when I'll be sure this is fixed!
