### ISSUE TITLE
[REQUEST] Let ICUE handle the lighting of disabled devices

### ISSUE THREAD

**Issue by HeasHeartfire** [Tagueo/icue-ambilight#28]
**Is your feature request related to a problem? Please describe.**
Kinda. If I disable a device then the light just turns off. It might be intended so I don't know.

**Describe the solution you'd like**
I'd like the lighting to not be changed if the device is disabled. In other words, let ICUE handle it.

**Describe alternatives you've considered**
It might be ideal to have a toggle or something so everyone can choose the behavior they want.

Great work by the way.

**Comment by Tagueo** [comment]
Hi, sadly I believe that it is currently not possible with Corsair's SDK. However I'll implement soon a fallback for disabled devices so you will have a little bit more customization than just them being off.
