### ISSUE TITLE
[BUG] not controlling leds, Headset in devices

### ISSUE THREAD

**Issue by LaFlex** [Tagueo/icue-ambilight#30]
Since version 1.4 Icue ambilight no longer overrides my Corsair LEDS.

Installing version 1.4 or version 1.4.2 both no longer control my LEDS. Switching to version 1.3 or older works fine. I currently mostly use version 1.1 because of the 5760x1080 support without those annoying black bars covering most of my keyboard. I'm super eager to get 1.4+ working so i can get around those issues.

![error](https://user-images.githubusercontent.com/57323613/108643390-48fa2400-745f-11eb-9fc3-a7afd1317a2a.png)

**Comment by Tagueo** [comment]
Hi, sadly there is currently an issue with headsets than I'm not able to reliably fix because I do not have the specific hardware.
I'll get back to you when I will be able to provide an update.

**Comment by LaFlex** [comment]
I'm so glad you know that. 

Until you figure something out I can just install 1.4.2, unplug my headphones, start your software, then plug my headphones back in. Seems to work just fine as a crutch. I sent you 10 euro as a thanks. Been using your software for almost a year now.

Appreciate your work.

**Comment by Tagueo** [comment]
Thanks a lot for the donation, I really appreciate it!
As soon as I get time I'll try to fix this and the related issues.

Thanks again 😀
