### ISSUE TITLE
doesn't work when added to the startup folder

### ISSUE THREAD

**Issue by miss-tech** [Tagueo/icue-ambilight#6]
I added icue-ambilight to the startup folder under c:\users\usera\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup and after this the software was unable to capture the screen. Removing the the shortcut from the startup folder resolved the problem.

**Comment by Tagueo** [comment]
Hi, I'm pretty confident that that this issue happens because icue-ambilight launches faster than icue at startup, and that icue needs to be launched for the sdk to work properly. I don't think I can do anything about this for now.
